name: fontify
version: 0.3.0-nullsafety.0
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/westracer/fontify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  collection: ^1.15.0
  logger: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  path_parsing: ^0.2.0
  recase: ^4.0.0
  vector_math: ^2.1.0
  xml: ^5.1.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  
executables:
  fontify: fontify